export const SITE = {
  website: "https://prop-auto-hack.com/",
  author: "はちまき",
  profile: "https://x.com/hachi_ni_isan",
  desc: "プロップファームをEA（自動売買）で攻略する実践記録。MT5・cTrader対応。バックテスト検証、成績公開、環境構築ガイドなど。",
  title: "プロップ自動攻略",
  ogImage: "og-image.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ja",
  timezone: "Asia/Tokyo",
} as const;
